@host = localhost:5000

// Access a Secured API Endpoint
GET http://{{host}}/auth/ping HTTP/1.1
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTU4MjY0MTMsIm5hbWUiOiJ1c2VyMyIsImVtYWlsIjoidXNlcjNAZm9vLmZvbyJ9.T6MORVKgt2cqrsNEhG1v44TbEPTpIAXGYjpPlQ197xA

###