version: '2'
services:
  backend:
    image: ghcr.io/esacteksab/wilddata:local
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - /var/tmp/wtfizit-data:/var/lib/postgresql/data/
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    env_file:
      - .env
