name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint pr title
        uses: amannn/action-semantic-pull-request@cfb60706e18bc85e8aec535e3c577abe8f70378e # v5.5.2
        with:
          wip: true
          types: |
            build
            chore
            ci
            dev
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}